// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OnlineShop.Models.DB
{
    /// <summary>
    /// 購物車紀錄
    /// </summary>
    [Table("cart")]
    [Index(nameof(ProductId), Name = "FK_cart_product")]
    [Index(nameof(UId), Name = "FK_cart_user")]
    public partial class Cart
    {
        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Column("u_id")]
        public long UId { get; set; }
        [Column("product_id")]
        public long ProductId { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }
        [Column("created_at", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("updated_at", TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty("Cart")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(UId))]
        [InverseProperty(nameof(User.Cart))]
        public virtual User UIdNavigation { get; set; }
    }
}